In [146]:
import os

print(os.path.exists("../models/encoder.pkl"))
print(os.path.exists("../models/kmeans_model.pkl"))
print(os.path.exists("../outputs/final_clustered_data.csv"))

True
True
True

In [147]:
recommend_restaurants("AB FOODS POINT")

                       name    city                     cuisine rating
1         Janta Sweet House  Abohar               Sweets,Bakery    4.4
3                 Singh Hut  Abohar            Fast Food,Indian    3.7
4             GRILL MASTERS  Abohar  Italian-American,Fast Food     --
5                 Sam Uncle  Abohar                 Continental    3.6
8  Hinglaj Kachori Bhandhar  Abohar                Snacks,Chaat    4.2

In [148]:
cleaned_df['name'].iloc[0]

'AB FOODS POINT'

In [149]:
def recommend_restaurants(restaurant_name, n=5):

    if restaurant_name not in restaurant_indices:
        return "Restaurant not found"

    idx = restaurant_indices[restaurant_name]

    cluster = cleaned_df.loc[idx, 'cluster']

    recommendations = cleaned_df[
        (cleaned_df['cluster'] == cluster) &
        (cleaned_df.index != idx)
    ]

    return recommendations[
        ['name', 'city', 'cuisine', 'rating']
    ].head(n)

In [150]:
restaurant_indices = pd.Series(
    cleaned_df.index,
    index=cleaned_df['name']
).drop_duplicates()

In [151]:
import joblib

joblib.dump(kmeans, "../models/kmeans_model.pkl")

['../models/kmeans_model.pkl']

In [152]:
cleaned_df.to_csv("../outputs/final_clustered_data.csv", index=False)

In [153]:
cleaned_df[['name', 'city', 'cuisine', 'cluster']].head()

                name    city                     cuisine  cluster
0     AB FOODS POINT  Abohar            Beverages,Pizzas        0
1  Janta Sweet House  Abohar               Sweets,Bakery        0
2  theka coffee desi  Abohar                   Beverages       40
3          Singh Hut  Abohar            Fast Food,Indian        0
4      GRILL MASTERS  Abohar  Italian-American,Fast Food        0

In [154]:
cleaned_df['cluster'] = clusters

In [155]:
kmeans = MiniBatchKMeans(
    n_clusters=20,
    random_state=42,
    batch_size=1000
)

In [156]:
kmeans = MiniBatchKMeans(
    n_clusters=50,
    random_state=42,
    batch_size=1000
)

In [157]:
from sklearn.cluster import MiniBatchKMeans

In [158]:
cleaned_df.shape

(148255, 12)

In [159]:
encoded_df.shape

(148255, 2952)

In [160]:
import pandas as pd

In [161]:
from sklearn.cluster import MiniBatchKMeans

In [162]:
import pandas as pd

In [163]:
encoded_df = pd.read_csv("../outputs/encoded_data.csv")

MemoryError: Unable to allocate 3.26 GiB for an array with shape (2952, 148255) and data type float64

In [ ]:
import pandas as pd

cleaned_df = pd.read_csv("../outputs/cleaned_data.csv")

In [ ]:
len(cleaned_df), len(encoded_df)

(148255, 148255)

In [ ]:
encoded_df.shape

(148255, 2952)

In [ ]:
import pandas as pd

encoded_df = pd.DataFrame(encoded_features)

NameError: name 'encoded_features' is not defined

In [ ]:
import os
os.path.exists("../models/encoder.pkl")

In [ ]:
import pickle

with open("../models/encoder.pkl", "wb") as f:
    pickle.dump(encoder, f)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
encoded_df.head()

In [ ]:
encoded_df.to_csv("../outputs/encoded_data.csv", index=False)

In [ ]:
encoded_df.shape

In [ ]:
encoded_df = pd.DataFrame(encoded_features)

In [ ]:
type(encoded_features)

In [ ]:
encoded_features = encoder.fit_transform(cleaned_df[['city', 'cuisine']])

In [ ]:
encoded_features.shape

In [ ]:
encoded_features = encoder.fit_transform(cleaned_df[['city', 'cuisine']])

In [ ]:
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
cleaned_df.to_csv("../outputs/cleaned_data.csv", index=False)

In [ ]:
cleaned_df.shape

In [ ]:
cleaned_df = df.dropna()

In [ ]:
df.duplicated().sum()

In [ ]:
df.isnull().sum()

In [ ]:
df.columns

In [ ]:
df.shape

In [ ]:
df = pd.read_csv("../data/swiggy.csv")

In [ ]:
import pandas as pd